perf: sumac release support
eduNEXT/eox-tagging pull request #124
Opened 2024-12-19 21:48 UTC by luisfelipec95

## Description

This PR aims to support the new Sumac Release

## Testing instructions

1, Create a Sumac environment using Tutor or TVM.
2. Install eox-tagging using this branch you can follow the official [tutor documentation](https://docs.tutor.overhang.io/configuration.html#installing-extra-xblocks-and-requirements).
3. Follow the [test cases ](https://docs.google.com/document/d/1VnjGF6Ri1Bvgbcd8AulM5jt68U7BmYJLVV2H5Bi5VOg/edit?tab=t.0)file.

2024-12-20 14:34 UTC, magajh requested changes
@luisfelipec95 thanks, just a couple of comments:

- Please review https://github.com/eduNEXT/eox-tagging/pull/123
- Since we are removing support for python 3.8, I believe this constraint is no longer needed https://github.com/eduNEXT/eox-tagging/blob/master/requirements/constraints.txt#L15-L16, so we'll need to remove it and update requirements
- We need to update the classifiers in the setup file https://github.com/eduNEXT/eox-tagging/blob/master/setup.py#L80

2024-12-20 14:34 UTC, magajh commented on README.rst
Lets please update the compatibility table for Quince, since we are removing the support for python 3.8 in this PR, we need to make
Quince < 9.0.0

2024-12-20 14:35 UTC, magajh commented
@luisfelipec95 why are we removing support for python 3.8 here? where you getting problems when trying to upgrade the requirements?

2024-12-20 16:22 UTC, luisfelipec95 commented
> @luisfelipec95 why are we removing support for python 3.8 here? where you getting problems when trying to upgrade the requirements?

https://github.com/eduNEXT/eox-tagging/actions/runs/12421325902/job/34680763565

2024-12-20 17:24 UTC, magajh commented
@luisfelipec95 have we tested this in stage yet?

2024-12-27 14:49 UTC, jignaciopm approved these changes
LGTM! @luisfelipec95 @magajh i tested this in stage and all it great!

2024-12-27 18:23 UTC, merged